version: "2"
services:
  node:
    working_dir: /tutorial_react
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/tutorial_react
    expose:
      - "8081"
    command: "npm start"
